### ISSUE TITLE
Support for more file extensions

### ISSUE THREAD

**Issue by folsen** [lukexi/halive#11]
Currently it looks like the supported file extensions for watching are hardcoded. I'd like to be able to supply a list of extra file formats to watch as a command-line argument (or just add more of them). The file format I'd like to watch right now is `.hamlet` files that are the templates in my webapp.

**Comment by lukexi** [comment]
For sure, I'd like this too! Mainly just laziness dealing with all the command line complication (there are arguments to halive itself + arguments to the underlying GHC instance + arguments to the target program to contend with). Would a `.halive.yaml` or something work ok too?

**Comment by folsen** [comment]
A `.halive.yaml` file would probably be great actually! Also indicates at first-glance of a repo that it supports running with halive.
