### ISSUE TITLE
Halive can't find cabal generated Paths

### ISSUE THREAD

**Issue by schell** [lukexi/halive#15]
This might not be a bug so much as a misunderstanding. How do I tell `halive` about the Paths_my_exe module generated by cabal? I need this in order to access data files packaged with cabal.

```
src/Main.hs:14:8:
    Could not find module ‘Paths_gelatin_example’
    Use -v to see a list of the files searched for.
```

**Comment by lukexi** [comment]
Hi Schell! : ))

Does passing the path to it as an include dir help?
As in:
https://github.com/lukexi/halive#passing-command-line-arguments

so like
`halive src/Main.hs path/where/Paths_gelative_example/lives`

??

**Comment by schell** [comment]
Part of the problem is that I'm not quite sure where the module lives, since it's generated by `cabal` (or in this case `cabal` via `stack`). I'll see what I can find and post any updates here :) I hope all is well!

**Comment by lukexi** [comment]
Hmm, maybe something like

```
halive src/Main.hs `stack path --dist-dir`
```
?? (I haven't needed a Paths file in a while so I forget where it puts them but it's gotta be _one_ of those `stack path` entries : )

**Comment by schell** [comment]
I revisited this today and figured it out. The answer is to include `(stack path --dist-dir)/build/autogen`.

Example using fish shell:
```fish
halive app/Example.hs src/ (stack path --dist-dir)/build/autogen
```
