### ISSUE TITLE
Latest version isn't released on hackage, and 0.1.0.7 doesn't build on GHC8

### ISSUE THREAD

**Issue by deepfire** [lukexi/halive#17]
Ditto.

**Comment by lukexi** [comment]
Ah yes, have been meaning to do a new release for a while : ) - will put one up!

**Comment by relrod** [comment]
+1

**Comment by lukexi** [comment]
Pushed! http://hackage.haskell.org/package/halive-0.1.1

**Comment by deepfire** [comment]
@lukexi, thank you!
