### ISSUE TITLE
errors are printed twice

### ISSUE THREAD

**Issue by gelisam** [lukexi/halive#4]
$ cat src/Main.hs
    main :: IO ()
    main = putStrLn "incomplete string
    $ halive src/Main.hs src/
    ██╗  ██╗ █████╗ ██╗     ██╗██╗   ██╗███████╗
    ██║  ██║██╔══██╗██║     ██║██║   ██║██╔════╝
    ███████║███████║██║     ██║██║   ██║█████╗  
    ██╔══██║██╔══██║██║     ██║╚██╗ ██╔╝██╔══╝  
    ██║  ██║██║  ██║███████╗██║ ╚████╔╝ ███████╗
    ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝  ╚══════╝
                      engaged
    
    src/Main.hs:2:35:
        lexical error in string/character literal at character '\n'
    
    src/Main.hs:2:35:
        lexical error in string/character literal at character '\n'

This is important to me because I usually want to focus on the first error, which is now twice as far back in the history (I have a simple custom patch which prints "===" between runs so I can see where the first error is)

**Comment by lukexi** [comment]
Thanks, that's annoying me too! I'll get it sorted.

**Comment by lukexi** [comment]
Let me know if that does the trick for you too!
