### ISSUE TITLE
halive-0.1.0.0 does not compile

### ISSUE THREAD

**Issue by peti** [lukexi/halive#6]
Citing from http://hydra.cryp.to/build/889395/log/raw:

~~~~~
Preprocessing executable 'halive' for halive-0.1.0.0...

exec/main.hs:1:8:
    Could not find module ‘Halive’
    Use -v to see a list of the files searched for.

exec/main.hs:2:8:
    Could not find module ‘Banner’
    Use -v to see a list of the files searched for.
~~~~~~

It appears that the published release tarball is incomplete.

**Comment by lukexi** [comment]
Hi Peti, Thanks! Yeah, I fixed that right away in 0.1.0.1 a few minutes later : ) http://hackage.haskell.org/package/halive-0.1.0.1 (can't pull a package, sadly!)
