### ISSUE TITLE
Build failure on GHC 7.8

### ISSUE THREAD

**Issue by bergmark** [lukexi/halive#8]
```
exec/main.hs:11:38: Not in scope: ‘<$>’
```

`(<$>)` was not in `Prelude` before 7.10. This can be fixed by importing it from `Control.Applicative`, or by using `base-compat`. If you don't care about backwards compatibility you can set a `base >= 4.8` lower bound.

I've revised current versions: http://hackage.haskell.org/package/halive/revisions/

**Comment by lukexi** [comment]
Thanks Adam! I uploaded a new version with the import for 7.8.

**Comment by bergmark** [comment]
Another GHC-7.8 failure popped up unfortunately! `mapM_` wasn't polymorphic over the container before  7.10.

```
src/Halive/Concurrent.hs:28:20:
    Couldn't match expected type ‘[ThreadId]’
                with actual type ‘Set ThreadId’
    In the second argument of ‘mapM_’, namely ‘threadIDs’
    In a stmt of a 'do' block: mapM_ killThread threadIDs
```

**Comment by lukexi** [comment]
Apologies and thanks : ) — fixed!

I set up a 7.8 environment so I can support it properly from here on out.
